spring.application.name=swipebites

spring.datasource.url=jdbc:postgresql://localhost:5432/swipebites
spring.datasource.username=swipebites
spring.datasource.password=password

spring.flyway.enabled=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

jwt.secret=4gJ6eB8tLwM2XkQ9YpRvNcHsFaKdLePmTzUxWvY1aBcDeFgHiJkLmNoPqRsTuVxY
jwt.expiration=86400000